### ISSUE TITLE
UT 99 (v436) - Execution could not continue. not found in the property string

### ISSUE THREAD

**Issue by r-a-sattarov** [dpjudas/SurrealEngine#125]
Steps to reproduce:
- click to "Game"/"Start Unreal Tournament"
- Press ESC
- click to "Game"/"Start Practice Session"
- select any map and start

![1](https://github.com/user-attachments/assets/706d5485-25ce-4f83-9141-d395e04e5541)

[surreal-engine-1-start-map.log](https://github.com/user-attachments/files/16266623/surreal-engine-1-start-map.log)
[surreal-engine-2-start-map.log](https://github.com/user-attachments/files/16266631/surreal-engine-2-start-map.log)

**Comment by LupertEverett** [comment]
Rather late but the reason this is happening is that we don't do class name parsings (like the one you're seeing on the error message) yet. It fallbacks to UObject parsing instead, which looks for a different format: `{prop1=value1, prop2=value2,...}` 

And since it cannot find anything of the sort, it throws an exception there.

**Comment by LupertEverett** [comment]
Latest changes fixed the issue on my end, could you try em out?

Also this means that I was off the mark with my initial idea. My bad.

**Comment by r-a-sattarov** [comment]
> Latest changes fixed the issue on my end, could you try em out?

Hi! Thanks, it fixed it.
