### ISSUE TITLE
Stable branch

### ISSUE THREAD

**Issue by mcneb10** [dpjudas/SurrealEngine#28]
I'd like to request that a stable branch of this repository. Right now there are errors in the master branch that I have to fix manually to get it to build properly.

**Comment by dpjudas** [comment]
Let me guess - you're running Linux?

It wouldn't help, since the real problem here is that the CI build scripts are currently broken, so we can't see the build fails without booting into Linux and compile it ourselves. Generally speaking the master branch is meant to be able to compile at all times (I never commit anything that doesn't compile on my own computer).

**Comment by dpjudas** [comment]
I just fixed the CI build scripts and the Linux build. So it should all be working now.

**Comment by mcneb10** [comment]
It does, thanks!
