### ISSUE TITLE
Use SDL2 instead of implementing code for different platforms

### ISSUE THREAD

**Issue by neuromancer** [dpjudas/SurrealEngine#9]
I think a library like SDL2 (or others) will simply a lot the handling of inputs and the window creation (and it can also solve the mouse lagging you saw in Linux). It will also allow this engine to run in MacOS without adding more code. Have you consider it?

**Comment by Firlaev-Hans** [comment]
SDL2 would also allow native Wayland support on Linux.

**Comment by dpjudas** [comment]
My attitude towards SDL2 aligns roughly with that of the ZDoom team. That is, I think native implementations for platforms are better than what SDL2 offers.

The only notable exception to this might be Linux, where the state of the native offerings have been stuck in time for a very very long time (X11's libraries works the same way they did in 1990 and Wayland seems to be stuck in some kind of dev hell never making it to my desktop). Gnome and KDE never built a proper shared base on top, etc etc. To solve that mess SDL2 probably would make life easier.

About macOS support, this isn't as simple as linking with SDL2 and be done with it. Any proper macOS port would have to produce universal fat binaries and not rely on brew and the macOS' unix compatibility. The window backend code is actually only a small part of the work required to make a good macOS version.

With all that said, I'm not against having a SDL backend in the codebase. Especially for Linux it might even be much better than the X11 version I wrote. If someone volunteers to writing one I will accept the PR.

The only thing to keep in mind is that I actually didn't port everything over to Linux yet. The engine has a visual debugger and will also soon get some kind of launch screen for game selection (like what zdoom has). I know SDL works well on Linux when it comes to the typical game behavior with one window meant for windows+fullscreen gaming - but how well does it work as a generalized window backend for non-game windows?

In any case, I'll soon improve the UI toolkit part to share its window class with the game window so that there's only one. After that if someone wants to write a SDL backend for it I'm fine with that. Only thing is I'll never enable it for Windows (don't want SDL2 as a dependency there) and eventually for macOS I'll also write my own backend. The SDL2 backend would be primarily to improve the Linux experience.

**Comment by leilei-** [comment]
I have a similar attitude towards SDL2 on OA.  My insistence to use SDL1 is "holding it back" to some SDL2 advocates who see that more as "dead code to replace" than to keep for compatibility maintenance (no doubt due to the SDL2=newer hype), and I wasn't ever against SDL2 for a backend as long as it wasn't done invasively (as most have been in the past). and i've had input locking issues with SDL2 on Windows


there's also the platform potential.  OA on SDL1 allows Win95 binaries, Win95 binaries allow me to use my old hardware (read: 1997~) better, and this drives my arting self to do more art on that.  I don't know what UTEngine's platform plans are, but IMO throwing it all to SDL2 would hurt those prospects.

**Comment by dpjudas** [comment]
For me it is a mixture of not needing SDL for my platform specific code (I'm well-versed enough in win32 that SDL doesn't make anything easier for me there) and generally wanting to keep 3rd party dependencies to an absolute minimum. When it is my own code I'm also in absolute control.

Supporting something like Win95 isn't really a goal here though. UTEngine's general CPU requirements makes that impossible. I'm using a lot of techniques that favors more readable code over higher performance. When UE1 was new they did not have the luxery to do that as all CPUs were so slow. Now it is far easier to keep a more reasonable balance between maintainable code and high performance.

Of course right now the code is extraordinary slow as the VM focuses more on reliable debug feedback than running the script fast. Once I can actually play some games in the engine I'll try fix the speed issue there. :)
